name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.16

      - name: Install dependencies
        run: corepack enable && corepack prepare pnpm@latest --activate
      
      - name: Export secrets to env
        run: |
          echo "VITE_BACKEND=${{ secrets.VITE_BACKEND }}" >> ./frontend/.env
      
      - name: Install dependencies
        run: pnpm install
        working-directory: ./frontend

      - name: Build site
        run: pnpm run build
        working-directory: ./frontend

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Empty S3 bucket
        run: |
          aws s3 rm s3://${{ secrets.S3_BUCKET_NAME }} --recursive

      - name: Upload to S3
        run: |
          aws s3 cp frontend/dist/ s3://${{ secrets.S3_BUCKET_NAME }} --recursive

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"
